const SEARCH_SERVER_ACTIONS = {
    GET_TRENDING: "GET_TRENDING",
    SEARCH_GIFS: "SEARCH_GIFS"
};

const SEARCH_VIEW_ACTIONS = {
    GET_TRENDING: "GET_TRENDING_VIEW",
    SEARCH_GIFS: "SEARCH_GIFS_VIEW"
};

export {SEARCH_SERVER_ACTIONS, SEARCH_VIEW_ACTIONS};
